let listaPlatos = [{
        id: 1,
        imgPLato: "./img/platos/desayuno01.jpg",
        precioPlato: 15.00,
        nombrePlato: "Desayuno de la Casa",
        descripcionPlato: "Huevos, pancakes y tocino",
        cantidad: 0,
        nombreCategoria: "Desayuno",

    },
    {
        id: 2,
        imgPLato: "./img/platos/ensalada01.jpg",
        precioPlato: 12.00,
        nombrePlato: "Ensalada César",
        descripcionPlato: "Con salsa ranch",
        cantidad: 0,
        nombreCategoria: "Ensalada",
    },
    {
        id: 3,
        imgPLato: "./img/platos/macarrones.jpg",
        precioPlato: 8.00,
        nombrePlato: "Macarrones con queso",
        descripcionPlato: "Queso parmesano",
        cantidad: 0,
        nombreCategoria: "Almuerzo, Cena",
    },
    {
        id: 4,
        imgPLato: "./img/platos/Hamburguesa.jpg",
        precioPlato: 9.00,
        nombrePlato: "Hamburguesa Clásica",
        descripcionPlato: "Con queso cheddar",
        cantidad: 0,
        nombreCategoria: "Almuerzo",
    },
    {
        id: 5,
        imgPLato: "./img/platos/pollo.jpg",
        precioPlato: 8.00,
        nombrePlato: "Pollo Asado",
        descripcionPlato: "Con papas fritas",
        cantidad: 0,
        nombreCategoria: "Almuerzo",
    },
    {
        id: 6,
        imgPLato: "./img/platos/pizza.jpg",
        precioPlato: 5.00,
        nombrePlato: "Pizza Margarita",
        descripcionPlato: "Tomate, mozzarella y albahaca",
        cantidad: 0,
        nombreCategoria: "Almuerzo",
    },
    {
        id: 7,
        imgPLato: "./img/platos/pescado.jpg",
        precioPlato: 20.00,
        nombrePlato: "Pescado a la plancha",
        descripcionPlato: "Pescado de temporada y verduras",
        cantidad: 0,
        nombreCategoria: "Cena",
    },

    {
        id: 8,
        imgPLato: "./img/platos/pieLimon.jpg",
        precioPlato: 5.00,
        nombrePlato: "Pie de Limón",
        descripcionPlato: "De la casa",
        cantidad: 0,
        nombreCategoria: "Postres",
    },
    {
        id: 9,
        imgPLato: "./img/platos/cheesecake.jpg",
        precioPlato: 5.00,
        nombrePlato: "Cheesecake",
        descripcionPlato: "Con frutos rojos",
        cantidad: 0,
        nombreCategoria: "Postres",
    },

    {
        id: 10,
        imgPLato: "./img/platos/vinoTinto.jpg",
        precioPlato: 3.50,
        nombrePlato: "Vino Tinto",
        descripcionPlato: "De la casa",
        cantidad: 0,
        nombreCategoria: "Bebidas",
    },
    {
        id: 11,
        imgPLato: "./img/platos/vinoBlanco.jpg",
        precioPlato: 3.50,
        nombrePlato: "Vino Blanco",
        descripcionPlato: "De la casa",
        cantidad: 0,
        nombreCategoria: "Bebidas",
    },
    {
        id: 12,
        imgPLato: "./img/platos/cerveza.jpg",
        precioPlato: 2.50,
        nombrePlato: "Cerveza",
        descripcionPlato: "De la casa",
        cantidad: 0,
        nombreCategoria: "Bebidas",
    },

]
let carritoDeCompra = [];